name: "Pre-Commit"

on:
  push:

jobs:
  pre-commit:
    name: "Pre-Commit"
    runs-on: "ubuntu-latest"

    steps:
    - name: "Checkout Repository"
      uses: "actions/checkout@v3"

    - name: "Install Python"
      uses: "actions/setup-python@v2"
      with:
        python-version: "3.10"

    - name: "Install poetry"
      run: "pip install --user poetry"

    - name: "Install dev environment"
      run: " poetry install --no-interaction --no-ansi"

    - name: "test"
      run: |
        cp config_test.yml config.yml
        poetry run pytest

    - name: "flake8"
      run: "poetry run flake8"

    - name: "black"
      run: "poetry run black --check ."

    - name: "mypy"
      run: "poetry run mypy ."
